Sq1 guilherme/s08 tela visualizacao dieta
DEVinHouse-Zucchetti/M3P-FrontEnd pull request #14
Opened 2024-03-26 22:52 UTC by 0Duarte

#Sq1 guilherme/s08 tela visualizacao dieta - Sem testes

2024-04-02 03:35 UTC, CarolineSampaio requested changes

2024-04-02 03:35 UTC, CarolineSampaio commented on src/views/StudentMealPlans.vue
> +    <v-container>
Devido ao menu, aqui precisa ser uma div com class container

```js
<div class="container">
....
```

2024-04-02 03:35 UTC, CarolineSampaio commented on src/views/StudentMealPlans.vue
> +                <v-timeline-item dot-color="grey-darken-1" size="small" fill-dot>
Acho que onde está usando grey-darken-1 poderia ser grey-darken-3 (#424242) pois é o que a maioria está utlizando e combinará melhor com o menu

2024-04-03 23:04 UTC, 0Duarte commented on src/views/StudentMealPlans.vue
> +                <v-timeline-item dot-color="grey-darken-1" size="small" fill-dot>
feito

2024-04-03 23:05 UTC, 0Duarte commented on src/views/StudentMealPlans.vue
> +    <v-container>
feito

2024-04-04 02:45 UTC, CarolineSampaio approved these changes
Tudo ok :D

2024-04-04 02:45 UTC, merged