Sq1-eduardo/s03-listagem usuario
DEVinHouse-Zucchetti/M3P-FrontEnd pull request #21
Opened 2024-03-30 23:35 UTC by EduardoPSRodrigues

Este pull request tem como objetivo listar todos os dados dos usuários cadastrados no sistema.
Por fim, foram realizados testes unitários para garantir o bom funcionamento das funcionalidades.

2024-03-31 23:47 UTC, CarolineSampaio requested changes
Somente inserir a linha que comentei para evitar que os erros simulados poluam o terminal e já está tudo certo!

2024-03-31 23:47 UTC, CarolineSampaio commented on src/views/User/ListUser.spec.js
> +
Tudo ok nos testes. Somente um detalhe, como estamos simulando um erro, ele vai para o terminal e acaba "poluindo" podemos inserir essas linhas para evitar que isso aconteça:

 ```js
 // Supressão de erro no console
    console.error = () => {}
 ````

2024-04-01 20:28 UTC, EduardoPSRodrigues commented on src/views/User/ListUser.spec.js
> +
Linha adicionada. Obrigado pela dica, realmente fica melhor.

2024-04-01 20:44 UTC, CarolineSampaio approved these changes
Tudo ok

2024-04-01 20:45 UTC, merged