Sq1-eduardo/s04-delecao-usuario
DEVinHouse-Zucchetti/M3P-FrontEnd pull request #23
Opened 2024-03-31 15:42 UTC by EduardoPSRodrigues

Este pull request tem como objetivo atualizar o status do usuário ao clicar no botão de ativar ou desativar. 
Ele inclui o tratamento de sucesso ou falha ao ativar o usuário, exibindo mensagens na tela. 
Após a atualização, os dados são renderizados novamente para refletir o novo status do usuário.

2024-03-31 23:50 UTC, CarolineSampaio requested changes
Excelente! Apenas dois pequenos detalhes e já poderemos fazer o merge!

2024-03-31 23:50 UTC, CarolineSampaio commented on src/services/UserService.js
> +    async uptadeStatusUserDelete(userId, body) {
alterar o nome da função de uptade para update. Lembrando de alterar também onde você chama esse service.

2024-03-31 23:50 UTC, CarolineSampaio commented on src/views/User/ListUser.vue
> +        const response = await UserService.uptadeStatusUserDelete(userId, body)
alterar o nome da função de uptade para update

2024-03-31 23:50 UTC, CarolineSampaio commented on src/views/User/ListUser.spec.js
> +})
Acho que seria interessante simular o funcionamento da ativação/desativação para garantir que está funcionando corretamente.

2024-04-01 20:40 UTC, EduardoPSRodrigues commented
Foi corrigido o nome da função e adicionado o teste unitário.

2024-04-01 20:49 UTC, CarolineSampaio approved these changes
Tudo ok

2024-04-01 20:49 UTC, merged